package com.openrubicon.core.api.enums;

public enum EventType {
    PLAYER_INTERACT,
    ENTITY_DAMAGE_BY_ENTITY,
    PLAYER_ITEM_DAMAGE,
    PLAYER_LAND_ON_GROUND,
    BLOCK_BREAK,
    MOVE,
    TAKING_DAMAGE,
    DEALING_DAMAGE,
    PLAYER_MOVED_LOCATION,
    PLAYER_STANDING_STILL,
    ENTITY_DEATH,
    ENTITY_DAMAGE,
    PLAYER_INTERACT_ENTITY
}
