name: RRPGCore
version: 0.0.1
authors: [ShawnClake, QuinnBast]
main: com.openrubicon.core.RRPGCore
depend: [Vault]
database: true
website: https://github.com/OpenRubiconProject
commands:
      rrpg:
               description: Spits out the current status of Rubicon and its versions
               usage: /rrpg
      rrpg discord restart:
               description: Restarts Discord
               usage: /rrpg restart discord
      rrpg connector restart:
               description: Restarts Connector
               usage: /rrpg restart connector
      rrpg config get <Key>:
               description: Retrieves the value of a configuration key
               usage: /rrpg config get <Config Key>
      rrpg test command:
               description: Tests a command
               usage: /rrpg test command

